var eventConfig =
{
  events: [
    {
      eventName:"taxi",
      eventTitle:chosenTranslationObj.EventTitles[0],
      eventKey:"a",
      variableLink:[]
    },
    {
      eventName:"hpShotSuccess",
      eventTitle:chosenTranslationObj.EventTitles[1],
      eventKey:"b",
      variableLink:[]
    },
    {
      eventName:"cargoUp",
      eventTitle:chosenTranslationObj.EventTitles[2],
      eventKey:"c",
      variableLink:[{"var":"cargoCount","amt":1}]
    },
    {
      eventName:"cargoDrop",
      eventTitle:chosenTranslationObj.EventTitles[3],
      eventKey:"d",
      variableLink:[{"var":"cargoCount","amt":-1}]
    },
    {
      eventName:"lowHubSuccess",
      eventTitle:chosenTranslationObj.EventTitles[4],
      eventKey:"e",
      variableLink:[{"var":"cargoCount","amt":-1}]
    },
    {
      eventName:"lowHubFail",
      eventTitle:chosenTranslationObj.EventTitles[5],
      eventKey:"f",
      variableLink:[{"var":"cargoCount","amt":-1}]
    },
    {
      eventName:"upperHubSuccess",
      eventTitle:chosenTranslationObj.EventTitles[6],
      eventKey:"g",
      variableLink:[{"var":"cargoCount","amt":-1}]
    },
    {
      eventName:"upperHubFail",
      eventTitle:chosenTranslationObj.EventTitles[7],
      eventKey:"h",
      variableLink:[{"var":"cargoCount","amt":-1}]
    },
    {
      eventName:"hangarClimb1",
      eventTitle:chosenTranslationObj.EventTitles[8],
      eventKey:"i",
      variableLink:[]
    },
    {
      eventName:"hangarClimb2",
      eventTitle:chosenTranslationObj.EventTitles[9],
      eventKey:"j",
      variableLink:[]
    },
    {
      eventName:"hangarClimbFail",
      eventTitle:chosenTranslationObj.EventTitles[10],
      eventKey:"k",
      variableLink:[]
    },
    {
      eventName:"hangarClimb3",
      eventTitle:chosenTranslationObj.EventTitles[11],
      eventKey:"l",
      variableLink:[]
    },
    {
      eventName:"hangarClimb4",
      eventTitle:chosenTranslationObj.EventTitles[12],
      eventKey:"m",
      variableLink:[]
    },
    {
      eventName:"defend",
      eventTitle:chosenTranslationObj.EventTitles[13],
      eventKey:"o",
      variableLink:[]
    },
  ],
  layouts: [
    {
      eventName:"taxi",
      buttonName:chosenTranslationObj.ButtonName[0],
      groupName:"auto",
      heightWeight:1,
      widthWeight:0.7
    },
    {
      eventName:"hpShotSuccess",
      buttonName:chosenTranslationObj.ButtonName[1],
      groupName:"auto",
      heightWeight:1,
      widthWeight:0.3
    },
    {
      eventName:"cargoUp",
      buttonName:chosenTranslationObj.ButtonName[2],
      groupName:"cargo",
      heightWeight:1,
      widthWeight:0.55
    },
    {
      eventName:"cargoDrop",
      buttonName:chosenTranslationObj.ButtonName[3],
      groupName:"cargo",
      heightWeight:1,
      widthWeight:0.45
    },
    {
      eventName:"lowHubSuccess",
      buttonName:chosenTranslationObj.ButtonName[4],
      groupName:"lowhub",
      heightWeight:1,
      widthWeight:0.7
    },
    {
      eventName:"lowHubFail",
      buttonName:chosenTranslationObj.ButtonName[5],
      groupName:"lowhub",
      heightWeight:1,
      widthWeight:0.3
    },
    {
      eventName:"upperHubSuccess",
      buttonName:chosenTranslationObj.ButtonName[6],
      groupName:"upperhub",
      heightWeight:1,
      widthWeight:0.7
    },
    {
      eventName:"upperHubFail",
      buttonName:chosenTranslationObj.ButtonName[7],
      groupName:"upperhub",
      heightWeight:1,
      widthWeight:0.3
    },
    {
      eventName:"hangarClimb1",
      buttonName:chosenTranslationObj.ButtonName[8],
      groupName:"hangarclimb",
      heightWeight:1,
      widthWeight:0.4
    },
    {
      eventName:"hangarClimb2",
      buttonName:chosenTranslationObj.ButtonName[9],
      groupName:"hangarclimb",
      heightWeight:1,
      widthWeight:0.166
    },
    {
      eventName:"hangarClimbFail",
      buttonName:chosenTranslationObj.ButtonName[10],
      groupName:"hangarclimb",
      heightWeight:1,
      widthWeight:0.267
    },
    {
      eventName:"hangarClimb3",
      buttonName:chosenTranslationObj.ButtonName[11],
      groupName:"hangartraversal",
      heightWeight:1,
      widthWeight:0.166
    },
    {
      eventName:"hangarClimb4",
      buttonName:chosenTranslationObj.ButtonName[12],
      groupName:"hangartraversal",
      heightWeight:1,
      widthWeight:0.166
    },
    {
      eventName:"defend",
      buttonName:chosenTranslationObj.ButtonName[13],
      groupName:"defense",
      heightWeight:1,
      widthWeight:0.5
    }

  ],
  variables: [
    {
      variableName:"cargoCount",
      variableTitle:"Cargo",
      variableLimit:[0,2],
      variableAmount:0
    }
  ],
  variableHeightWeight: 1,
  logHeightWeight: 2
}
